package com.calypsan.listenup.client.design.theme

import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.colorspace.ColorSpaces

/**
 * ListenUp brand orange - primary color for light theme fallback.
 * Used when dynamic color is unavailable (Android <12) or disabled by user.
 *
 * Defined in Display P3 color space for HDR support on compatible displays.
 * Displays ~25% more colors than sRGB, with richer saturation and vibrancy.
 */
val ListenUpOrange = Color(
    red = 1.0f,
    green = 0.42f,
    blue = 0.29f,
    colorSpace = ColorSpaces.DisplayP3
)

/**
 * Light color scheme with ListenUp orange as seed color.
 * Material 3 generates all tonal variations from this primary color.
 *
 * All generated colors inherit Display P3 color space from the seed color,
 * ensuring HDR support throughout the entire theme.
 */
internal val LightColorScheme = lightColorScheme(
    primary = ListenUpOrange
    // All other colors automatically generated by Material 3
)

/**
 * Helper function to create Display P3 colors for custom theme additions.
 * Use this for any future colors to maintain HDR support consistency.
 *
 * Example:
 * ```
 * val CustomAccent = p3Color(red = 0.2f, green = 0.8f, blue = 0.5f)
 * ```
 */
@Suppress("unused")
private fun p3Color(
    red: Float,
    green: Float,
    blue: Float,
    alpha: Float = 1.0f
) = Color(
    red = red,
    green = green,
    blue = blue,
    alpha = alpha,
    colorSpace = ColorSpaces.DisplayP3
)
