package com.calypsan.listenup.client.data.local.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.TypeConverters

/**
 * Room database for ListenUp client.
 *
 * Stores user data, books, and sync metadata for offline-first functionality.
 *
 * Schema versioning:
 * - v1: Initial schema with UserEntity only
 * - v2: Added BookEntity and SyncMetadataEntity for sync support
 * - v3: Added ChapterEntity
 * - v8: Added subtitle column to books table
 * - v9: Added FTS5 tables for full-text search (books_fts, contributors_fts, series_fts)
 * - v10: Added book_series junction table for many-to-many book-series relationships
 *
 * Migration strategy: Manual migrations provided for all version transitions
 * to preserve user data. Destructive migration disabled.
 */
@Database(
    entities = [
        UserEntity::class,
        BookEntity::class,
        SyncMetadataEntity::class,
        ChapterEntity::class,
        SeriesEntity::class,
        ContributorEntity::class,
        BookContributorCrossRef::class,
        BookSeriesCrossRef::class,
        PlaybackPositionEntity::class,
        PendingListeningEventEntity::class,
        DownloadEntity::class,
    ],
    version = 10,
    exportSchema = true,
)
@TypeConverters(Converters::class)
@ConstructedBy(ListenUpDatabaseConstructor::class)
abstract class ListenUpDatabase : RoomDatabase() {
    abstract fun userDao(): UserDao

    abstract fun bookDao(): BookDao

    abstract fun syncDao(): SyncDao

    abstract fun chapterDao(): ChapterDao

    abstract fun seriesDao(): SeriesDao

    abstract fun contributorDao(): ContributorDao

    abstract fun bookContributorDao(): BookContributorDao

    abstract fun bookSeriesDao(): BookSeriesDao

    abstract fun playbackPositionDao(): PlaybackPositionDao

    abstract fun pendingListeningEventDao(): PendingListeningEventDao

    abstract fun downloadDao(): DownloadDao

    abstract fun searchDao(): SearchDao
}

/**
 * Room database constructor for KMP.
 * This class is referenced by @ConstructedBy but implementation is generated by Room KSP.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object ListenUpDatabaseConstructor : RoomDatabaseConstructor<ListenUpDatabase>
