package com.calypsan.listenup.client.data.local.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.TypeConverters

/**
 * Room database for ListenUp client.
 *
 * Stores user data, books, and sync metadata for offline-first functionality.
 *
 * Schema is at v10 after the W4.4 restoration (reset from legacy to v1 baseline,
 * then bumped through v2-v10 as each junction split landed). Pre-launch policy:
 * `fallbackToDestructiveMigration(true)` is set on each `DatabaseModule` and
 * [Migrations] is a no-op stub. Before launch, flip the fallback to `false` and
 * populate a real migration chain in [Migrations]; the `@Database.exportSchema`
 * on-disk JSON for every version (v1-v10 prior to the cleanups) is the authoritative
 * source for writing those migrations.
 */
@Database(
    entities = [
        UserEntity::class,
        UserProfileEntity::class,
        BookEntity::class,
        SyncMetadataEntity::class,
        ChapterEntity::class,
        SeriesEntity::class,
        ContributorEntity::class,
        BookContributorCrossRef::class,
        ContributorAliasCrossRef::class,
        BookSeriesCrossRef::class,
        PlaybackPositionEntity::class,
        PendingOperationEntity::class,
        DownloadEntity::class,
        ServerEntity::class,
        CollectionEntity::class,
        ShelfEntity::class,
        ShelfBookCrossRef::class,
        TagEntity::class,
        BookTagCrossRef::class,
        GenreEntity::class,
        BookGenreCrossRef::class,
        AudioFileEntity::class,
        ListeningEventEntity::class,
        ActiveSessionEntity::class,
        ActivityEntity::class,
        UserStatsEntity::class,
        UserReadingSessionEntity::class,
        ReaderSessionCacheEntity::class,
        CoverDownloadTaskEntity::class,
    ],
    version = 10,
    exportSchema = true,
)
@TypeConverters(
    ValueClassConverters::class,
    Converters::class,
    PendingOperationConverters::class,
    CoverDownloadStatusConverter::class,
    StringListJsonConverter::class,
)
@ConstructedBy(ListenUpDatabaseConstructor::class)
@Suppress("TooManyFunctions")
abstract class ListenUpDatabase : RoomDatabase() {
    abstract fun userDao(): UserDao

    abstract fun userProfileDao(): UserProfileDao

    abstract fun bookDao(): BookDao

    abstract fun syncDao(): SyncDao

    abstract fun chapterDao(): ChapterDao

    abstract fun seriesDao(): SeriesDao

    abstract fun contributorDao(): ContributorDao

    abstract fun contributorAliasDao(): ContributorAliasDao

    abstract fun bookContributorDao(): BookContributorDao

    abstract fun bookSeriesDao(): BookSeriesDao

    abstract fun playbackPositionDao(): PlaybackPositionDao

    abstract fun pendingOperationDao(): PendingOperationDao

    abstract fun downloadDao(): DownloadDao

    abstract fun searchDao(): SearchDao

    abstract fun serverDao(): ServerDao

    abstract fun collectionDao(): CollectionDao

    abstract fun shelfDao(): ShelfDao

    abstract fun shelfBookDao(): ShelfBookDao

    abstract fun tagDao(): TagDao

    abstract fun genreDao(): GenreDao

    abstract fun audioFileDao(): AudioFileDao

    abstract fun listeningEventDao(): ListeningEventDao

    abstract fun activeSessionDao(): ActiveSessionDao

    abstract fun activityDao(): ActivityDao

    abstract fun userStatsDao(): UserStatsDao

    abstract fun userReadingSessionDao(): UserReadingSessionDao

    abstract fun readerSessionCacheDao(): ReaderSessionCacheDao

    abstract fun coverDownloadDao(): CoverDownloadDao
}

/**
 * Room database constructor for KMP.
 * The expect declaration is needed for commonMain compilation.
 * The actual implementations are generated by Room KSP for each platform (Android, iOS).
 */
@Suppress("NO_ACTUAL_FOR_EXPECT", "EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
expect object ListenUpDatabaseConstructor : RoomDatabaseConstructor<ListenUpDatabase> {
    override fun initialize(): ListenUpDatabase
}
